version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    tty: true
    networks:
      frontend:
        ipv4_address: 192.168.10.101


  api:
    build:
      context: .
      dockerfile: ./Docker/FastAPI/Dockerfile
    volumes:
      - ./FastAPI:/src
    tty: true
    networks:
      frontend:
        ipv4_address: 192.168.10.102
      backend:
        ipv4_address: 192.168.20.102


networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
