version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/FastAPI/Dockerfile
    volumes:
      - ./FastAPI/dockervenv:/src/.venv
      - ./FastAPI:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
